from enum import StrEnum


class Framework(StrEnum):
    EVIDENCE_BASED_WESTERN_MEDICINE = "EVIDENCE_BASED_WESTERN_MEDICINE"
    NUTRITION_SCIENCE = "NUTRITION_SCIENCE"
    PHYSICAL_ACTIVITY_SCIENCE = "PHYSICAL_ACTIVITY_SCIENCE"
    HOLISTIC_TRADITIONAL_SYSTEMS = "HOLISTIC_TRADITIONAL_SYSTEMS"
    LIFESTYLE_BEHAVIORAL_HEALTH = "LIFESTYLE_BEHAVIORAL_HEALTH"
    PREVENTIVE_MEDICINE = "PREVENTIVE_MEDICINE"


class SourceApprovalStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED_LIMITED = "APPROVED_LIMITED"
    APPROVED_ACTIVE = "APPROVED_ACTIVE"
    PAUSED = "PAUSED"
    BLOCKED = "BLOCKED"
    RETIRED = "RETIRED"


class SourceType(StrEnum):
    GUIDELINE_SOURCE = "GUIDELINE_SOURCE"
    PUBLIC_HEALTH_SOURCE = "PUBLIC_HEALTH_SOURCE"
    ACADEMIC_SOURCE = "ACADEMIC_SOURCE"
    HOSPITAL_EDUCATION_SOURCE = "HOSPITAL_EDUCATION_SOURCE"
    NUTRITION_GUIDANCE_SOURCE = "NUTRITION_GUIDANCE_SOURCE"
    EXERCISE_SCIENCE_SOURCE = "EXERCISE_SCIENCE_SOURCE"
    BEHAVIORAL_HEALTH_SOURCE = "BEHAVIORAL_HEALTH_SOURCE"
    TRADITIONAL_SYSTEM_SOURCE = "TRADITIONAL_SYSTEM_SOURCE"
    RECIPE_OR_LIFESTYLE_SOURCE = "RECIPE_OR_LIFESTYLE_SOURCE"
    DATASET_OR_API_SOURCE = "DATASET_OR_API_SOURCE"
    MANUAL_REFERENCE_SOURCE = "MANUAL_REFERENCE_SOURCE"
    CLINICAL_REPORT_SOURCE = "CLINICAL_REPORT_SOURCE"
    PRESCRIPTION_SOURCE = "PRESCRIPTION_SOURCE"


class DocumentStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    QUEUED_FOR_FETCH = "QUEUED_FOR_FETCH"
    FETCHED = "FETCHED"
    EXTRACTION_PENDING = "EXTRACTION_PENDING"
    EXTRACTED = "EXTRACTED"
    ENRICHMENT_PENDING = "ENRICHMENT_PENDING"
    ENRICHED = "ENRICHED"
    INDEXED = "INDEXED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class DocType(StrEnum):
    HTML_PAGE = "HTML_PAGE"
    PDF = "PDF"
    OTHER = "OTHER"


class DiscoveryMode(StrEnum):
    GENERIC = "GENERIC"
    FOCUSED = "FOCUSED"
    HYBRID = "HYBRID"


class DiscoveryDecision(StrEnum):
    INGEST_NOW = "INGEST_NOW"
    INGEST_LATER = "INGEST_LATER"
    REJECT_FOR_NOW = "REJECT_FOR_NOW"


class ReviewDecision(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    NEEDS_CHANGES = "NEEDS_CHANGES"
    ESCALATE = "ESCALATE"


class WorkflowStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class RunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class ExtractionQuality(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    FAILED = "FAILED"


class ValidationStatus(StrEnum):
    VALID = "VALID"
    INVALID = "INVALID"
    PENDING = "PENDING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class TagType(StrEnum):
    FRAMEWORK = "FRAMEWORK"
    TOPIC = "TOPIC"
    CONDITION = "CONDITION"
    SYMPTOM = "SYMPTOM"
    INTERVENTION = "INTERVENTION"
    SUPPLEMENT = "SUPPLEMENT"
    FOOD = "FOOD"
    NUTRIENT = "NUTRIENT"
    ACTIVITY = "ACTIVITY"
    POPULATION = "POPULATION"
    EVIDENCE_LEVEL = "EVIDENCE_LEVEL"
    CONTRAINDICATION = "CONTRAINDICATION"


class AssignedBy(StrEnum):
    RULE = "RULE"
    MODEL = "MODEL"
    MANUAL = "MANUAL"


class GraphNodeType(StrEnum):
    SOURCE = "SOURCE"
    DOCUMENT = "DOCUMENT"
    FRAMEWORK = "FRAMEWORK"
    TOPIC = "TOPIC"
    CONDITION = "CONDITION"
    SYMPTOM = "SYMPTOM"
    INTERVENTION = "INTERVENTION"
    SUPPLEMENT = "SUPPLEMENT"
    FOOD = "FOOD"


class GraphEdgeType(StrEnum):
    SOURCE_HAS_DOCUMENT = "SOURCE_HAS_DOCUMENT"
    DOCUMENT_BELONGS_TO_FRAMEWORK = "DOCUMENT_BELONGS_TO_FRAMEWORK"
    DOCUMENT_HAS_TOPIC = "DOCUMENT_HAS_TOPIC"
    DOCUMENT_MENTIONS_CONDITION = "DOCUMENT_MENTIONS_CONDITION"
    DOCUMENT_MENTIONS_SYMPTOM = "DOCUMENT_MENTIONS_SYMPTOM"
    DOCUMENT_MENTIONS_INTERVENTION = "DOCUMENT_MENTIONS_INTERVENTION"
    DOCUMENT_MENTIONS_SUPPLEMENT = "DOCUMENT_MENTIONS_SUPPLEMENT"
    DOCUMENT_MENTIONS_FOOD = "DOCUMENT_MENTIONS_FOOD"
    TOPIC_RELATED_TO_TOPIC = "TOPIC_RELATED_TO_TOPIC"


class GraphProvenance(StrEnum):
    EXTRACTION = "EXTRACTION"
    ENRICHMENT = "ENRICHMENT"
    MANUAL = "MANUAL"


class ModelTaskType(StrEnum):
    SOURCE_CLASSIFICATION = "SOURCE_CLASSIFICATION"
    DOCUMENT_SUMMARY = "DOCUMENT_SUMMARY"
    FRAMEWORK_TAGGING = "FRAMEWORK_TAGGING"
    FACT_EXTRACTION = "FACT_EXTRACTION"
    KEYWORD_EXTRACTION = "KEYWORD_EXTRACTION"
    GRAPH_EDGE_SUGGESTION = "GRAPH_EDGE_SUGGESTION"


class ReviewEntityType(StrEnum):
    SOURCE = "SOURCE"
    DOCUMENT = "DOCUMENT"
    ENRICHMENT = "ENRICHMENT"
