"""add clinical quality metadata

Revision ID: 38ed2288cee3
Revises: a1b2c3d4e5f6
Create Date: 2026-05-29 22:06:14.814166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ed2288cee3'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_registry', sa.Column('evidence_grade', sa.String(length=20), nullable=True))
    op.add_column('document_registry', sa.Column('study_type', sa.String(length=100), nullable=True))
    op.add_column('document_registry', sa.Column('methodology_critique', sa.Text(), nullable=True))
    op.add_column('knowledge_fact', sa.Column('subject_type', sa.String(length=50), nullable=True))
    op.add_column('knowledge_fact', sa.Column('object_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_fact', 'object_type')
    op.drop_column('knowledge_fact', 'subject_type')
    op.drop_column('document_registry', 'methodology_critique')
    op.drop_column('document_registry', 'study_type')
    op.drop_column('document_registry', 'evidence_grade')
    # ### end Alembic commands ###
