"""add_deduplication_indices

Revision ID: 4175f3e98557
Revises: 9c3229c6e56f
Create Date: 2026-05-14 07:56:19.501689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4175f3e98557'
down_revision: Union[str, None] = '9c3229c6e56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_audit_log', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('admin_audit_log', 'entity_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('admin_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidate_discovery_run', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='runstatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::runstatus"))
    op.alter_column('candidate_discovery_run', 'candidate_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('candidate_discovery_run', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidate_document_evaluation', 'run_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('candidate_document_evaluation', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('candidate_document_evaluation', 'decision',
               existing_type=postgresql.ENUM('INGEST_NOW', 'INGEST_LATER', 'REJECT_FOR_NOW', name='discoverydecision'),
               nullable=False,
               existing_server_default=sa.text("'INGEST_NOW'::discoverydecision"))
    op.alter_column('candidate_document_evaluation', 'evaluated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chunk_run', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chunk_run', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='runstatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::runstatus"))
    op.alter_column('chunk_run', 'chunk_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('discovery_filter_profile', 'max_candidates',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('discovery_filter_profile', 'per_source_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('20'))
    op.alter_column('discovery_filter_profile', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('discovery_filter_profile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_registry', 'source_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('document_registry', 'doc_type',
               existing_type=postgresql.ENUM('HTML_PAGE', 'PDF', 'OTHER', name='doctype'),
               nullable=False,
               existing_server_default=sa.text("'HTML_PAGE'::doctype"))
    op.alter_column('document_registry', 'status',
               existing_type=postgresql.ENUM('DISCOVERED', 'QUEUED_FOR_FETCH', 'FETCHED', 'EXTRACTION_PENDING', 'EXTRACTED', 'ENRICHMENT_PENDING', 'ENRICHED', 'INDEXED', 'REVIEW_REQUIRED', 'FAILED', 'REJECTED', name='documentstatus'),
               nullable=False,
               existing_server_default=sa.text("'DISCOVERED'::documentstatus"))
    op.alter_column('document_registry', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('document_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_registry', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_version', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('document_version', 'version_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('document_version', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('enrichment_run', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('enrichment_run', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='runstatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::runstatus"))
    op.alter_column('extraction_run', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('extraction_run', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='runstatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::runstatus"))
    op.alter_column('fetch_run', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('fetch_run', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='runstatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::runstatus"))
    op.alter_column('graph_edge', 'from_node_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('graph_edge', 'to_node_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('graph_edge', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('graph_edge', 'provenance',
               existing_type=postgresql.ENUM('EXTRACTION', 'ENRICHMENT', 'MANUAL', name='graphprovenance'),
               nullable=False,
               existing_server_default=sa.text("'ENRICHMENT'::graphprovenance"))
    op.alter_column('graph_edge', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('graph_node', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('graph_run', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('graph_run', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='runstatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::runstatus"))
    op.alter_column('graph_run', 'nodes_created',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('graph_run', 'edges_created',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('job_error', 'workflow_run_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('job_error', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_chunk', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('knowledge_chunk', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_fact', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('knowledge_fact', 'validation_status',
               existing_type=postgresql.ENUM('VALID', 'INVALID', 'PENDING', 'REVIEW_REQUIRED', name='validationstatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::validationstatus"))
    op.alter_column('knowledge_fact', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_summary', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('knowledge_summary', 'validation_status',
               existing_type=postgresql.ENUM('VALID', 'INVALID', 'PENDING', 'REVIEW_REQUIRED', name='validationstatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::validationstatus"))
    op.alter_column('knowledge_summary', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_tag', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('knowledge_tag', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('knowledge_tag', 'assigned_by',
               existing_type=postgresql.ENUM('RULE', 'MODEL', 'MANUAL', name='assignedby'),
               nullable=False,
               existing_server_default=sa.text("'MODEL'::assignedby"))
    op.alter_column('knowledge_tag', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('review_queue', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('review_queue', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('review_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('source_framework_map', 'source_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('source_framework_map', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('source_framework_map', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('source_policy', 'source_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('source_registry', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('source_registry', 'trust_tier',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('source_registry', 'approval_status',
               existing_type=postgresql.ENUM('CANDIDATE', 'UNDER_REVIEW', 'APPROVED_LIMITED', 'APPROVED_ACTIVE', 'PAUSED', 'BLOCKED', 'RETIRED', name='sourceapprovalstatus'),
               nullable=False,
               existing_server_default=sa.text("'CANDIDATE'::sourceapprovalstatus"))
    op.alter_column('source_registry', 'freshness_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('14'))
    op.alter_column('source_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('source_registry', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('source_review', 'source_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('source_review', 'actor',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('source_review', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_run', 'status',
               existing_type=postgresql.ENUM('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowstatus'),
               nullable=False,
               existing_server_default=sa.text("'RUNNING'::workflowstatus"))
    op.alter_column('workflow_run', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    
    # Custom Unique Constraints for Deduplication
    op.create_unique_constraint('uq_knowledge_fact_content', 'knowledge_fact', ['document_id', 'subject', 'predicate', 'object'])
    op.create_unique_constraint('uq_knowledge_tag_content', 'knowledge_tag', ['document_id', 'tag_type', 'tag_value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_run', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_run', 'status',
               existing_type=postgresql.ENUM('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowstatus'),
               nullable=True,
               existing_server_default=sa.text("'RUNNING'::workflowstatus"))
    op.alter_column('source_review', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('source_review', 'actor',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('source_review', 'source_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('source_registry', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('source_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('source_registry', 'freshness_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('14'))
    op.alter_column('source_registry', 'approval_status',
               existing_type=postgresql.ENUM('CANDIDATE', 'UNDER_REVIEW', 'APPROVED_LIMITED', 'APPROVED_ACTIVE', 'PAUSED', 'BLOCKED', 'RETIRED', name='sourceapprovalstatus'),
               nullable=True,
               existing_server_default=sa.text("'CANDIDATE'::sourceapprovalstatus"))
    op.alter_column('source_registry', 'trust_tier',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('source_registry', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('source_policy', 'source_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('source_framework_map', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('source_framework_map', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('source_framework_map', 'source_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('review_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('review_queue', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('review_queue', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('knowledge_tag', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_tag', 'assigned_by',
               existing_type=postgresql.ENUM('RULE', 'MODEL', 'MANUAL', name='assignedby'),
               nullable=True,
               existing_server_default=sa.text("'MODEL'::assignedby"))
    op.alter_column('knowledge_tag', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('knowledge_tag', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('knowledge_summary', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_summary', 'validation_status',
               existing_type=postgresql.ENUM('VALID', 'INVALID', 'PENDING', 'REVIEW_REQUIRED', name='validationstatus'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::validationstatus"))
    op.alter_column('knowledge_summary', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('knowledge_fact', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_fact', 'validation_status',
               existing_type=postgresql.ENUM('VALID', 'INVALID', 'PENDING', 'REVIEW_REQUIRED', name='validationstatus'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::validationstatus"))
    op.alter_column('knowledge_fact', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('knowledge_chunk', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_chunk', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('job_error', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_error', 'workflow_run_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('graph_run', 'edges_created',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('graph_run', 'nodes_created',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('graph_run', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='runstatus'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::runstatus"))
    op.alter_column('graph_run', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('graph_node', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('graph_edge', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('graph_edge', 'provenance',
               existing_type=postgresql.ENUM('EXTRACTION', 'ENRICHMENT', 'MANUAL', name='graphprovenance'),
               nullable=True,
               existing_server_default=sa.text("'ENRICHMENT'::graphprovenance"))
    op.alter_column('graph_edge', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('graph_edge', 'to_node_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('graph_edge', 'from_node_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('fetch_run', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='runstatus'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::runstatus"))
    op.alter_column('fetch_run', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('extraction_run', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='runstatus'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::runstatus"))
    op.alter_column('extraction_run', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('enrichment_run', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='runstatus'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::runstatus"))
    op.alter_column('enrichment_run', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('document_version', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_version', 'version_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('document_version', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('document_registry', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_registry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_registry', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('document_registry', 'status',
               existing_type=postgresql.ENUM('DISCOVERED', 'QUEUED_FOR_FETCH', 'FETCHED', 'EXTRACTION_PENDING', 'EXTRACTED', 'ENRICHMENT_PENDING', 'ENRICHED', 'INDEXED', 'REVIEW_REQUIRED', 'FAILED', 'REJECTED', name='documentstatus'),
               nullable=True,
               existing_server_default=sa.text("'DISCOVERED'::documentstatus"))
    op.alter_column('document_registry', 'doc_type',
               existing_type=postgresql.ENUM('HTML_PAGE', 'PDF', 'OTHER', name='doctype'),
               nullable=True,
               existing_server_default=sa.text("'HTML_PAGE'::doctype"))
    op.alter_column('document_registry', 'source_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('discovery_filter_profile', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('discovery_filter_profile', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('discovery_filter_profile', 'per_source_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('20'))
    op.alter_column('discovery_filter_profile', 'max_candidates',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('chunk_run', 'chunk_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('chunk_run', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='runstatus'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::runstatus"))
    op.alter_column('chunk_run', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('candidate_document_evaluation', 'evaluated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidate_document_evaluation', 'decision',
               existing_type=postgresql.ENUM('INGEST_NOW', 'INGEST_LATER', 'REJECT_FOR_NOW', name='discoverydecision'),
               nullable=True,
               existing_server_default=sa.text("'INGEST_NOW'::discoverydecision"))
    op.alter_column('candidate_document_evaluation', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('candidate_document_evaluation', 'run_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('candidate_discovery_run', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidate_discovery_run', 'candidate_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('candidate_discovery_run', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='runstatus'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::runstatus"))
    op.alter_column('admin_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('admin_audit_log', 'entity_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('admin_audit_log', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
               
    # Custom Unique Constraints removal
    op.drop_constraint('uq_knowledge_fact_content', 'knowledge_fact', type_='unique')
    op.drop_constraint('uq_knowledge_tag_content', 'knowledge_tag', type_='unique')
    # ### end Alembic commands ###
