"""add_validated_to_validation_status

Revision ID: fc8bcf883b6f
Revises: 4175f3e98557
Create Date: 2026-05-14 08:06:07.508358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8bcf883b6f'
down_revision: Union[str, None] = '4175f3e98557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE validationstatus ADD VALUE 'VALIDATED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
