"""Add intelligent prioritization

Revision ID: fe0609c80dfa
Revises: fc8bcf883b6f
Create Date: 2026-05-16 23:06:21.901963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe0609c80dfa'
down_revision: Union[str, None] = 'fc8bcf883b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_registry', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('document_registry', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('document_registry', sa.Column('evaluation_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('knowledge_fact', 'is_hallucination',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_fact', 'is_hallucination',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('document_registry', 'evaluation_metrics')
    op.drop_column('document_registry', 'metadata_json')
    op.drop_column('document_registry', 'priority_score')
    # ### end Alembic commands ###
