"""Add intelligent prioritization

Revision ID: fe0609c80dfa
Revises: fc8bcf883b6f
Create Date: 2026-05-16 23:06:21.901963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe0609c80dfa'
down_revision: Union[str, None] = 'fc8bcf883b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_registry', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('document_registry', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('document_registry', sa.Column('evaluation_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # Add columns that were missing from the initial schema
    op.add_column('knowledge_fact', sa.Column('is_hallucination', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('knowledge_fact', sa.Column('critique', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_fact', 'critique')
    op.drop_column('knowledge_fact', 'is_hallucination')
    op.drop_column('document_registry', 'evaluation_metrics')
    op.drop_column('document_registry', 'metadata_json')
    op.drop_column('document_registry', 'priority_score')
    # ### end Alembic commands ###
